blueprint:
  name: Motion activated light
  description: Turn on a light for N minutes with X brightness when motion is detected.
  domain: automation
  author: ludeeus
  homeassistant:
    min_version: "2023.6.0"
  input:
    motion_entity:
      name: Motion entity
      description: The Motion sensor to trigger on
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: motion
    light_target:
      name: Light targets
      description: The lights that should be controlled
      selector:
        target:
          entity:
            domain: light
    minutes:
      name: Minuttes
      description: How long should the light stay on for
      default: 3
      selector:
        number:
          max: 60
          min: 0
    brightness:
      name: Default Brightness
      description: What brightness should the light be set to on motion
      default: 70
      selector:
        number:
          max: 100
          min: 1
          unit_of_measurement: "%"
    color_temp:
      name: Default Color Temperature
      description: Color temperature during the day (higher = cooler/bluer, lower = warmer/yellower)
      default: 4000
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: "K"
    night_mode_brightness:
      name: Night Mode Brightness
      description: What brightness should the light be set to during night mode
      default: 50
      selector:
        number:
          max: 100
          min: 1
          unit_of_measurement: "%"
    night_mode_color_temp:
      name: Night Mode Color Temperature
      description: Color temperature during night mode (lower = warmer, like candlelight)
      default: 2700
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: "K"
    night_mode_start:
      name: Night Mode Start
      description: When should night mode brightness begin? (e.g., evening)
      default: "20:00:00"
      selector:
        time:
    night_mode_end:
      name: Night Mode End
      description: When should night mode brightness end? (e.g., morning)
      default: "07:00:00"
      selector:
        time:
    condition_block:
      name: Turn on Conditions
      description: Add in any optional conditions that would need to be True before the action sequense runs.
      default: []
      selector:
        condition:
    turn_off_condition_block:
      name: Turn off Conditions
      description: Add in any optional conditions that would need to be True before the turn off action runs.
      default: []
      selector:
        condition:

mode: restart
variables:
  brightness: !input brightness
  color_temp: !input color_temp
  night_mode_brightness: !input night_mode_brightness
  night_mode_color_temp: !input night_mode_color_temp
  night_mode_start: !input night_mode_start
  night_mode_end: !input night_mode_end

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: 'on'

condition: !input condition_block

action:
  - service: light.turn_on
    data:
      brightness_pct: >-
        {% set start = today_at(night_mode_start) if night_mode_start else none %}
        {% set end = today_at(night_mode_end) if night_mode_end else none %}
        {% set is_night_mode = false %}
        {% if start and end %}
          {% if start > end %}
            {% set is_night_mode = now() >= start or now() < end %}
          {% else %}
            {% set is_night_mode = start <= now() < end %}
          {% endif %}
        {% endif %}
        {{ night_mode_brightness if is_night_mode else brightness }}
      color_temp_kelvin: >-
        {% set start = today_at(night_mode_start) if night_mode_start else none %}
        {% set end = today_at(night_mode_end) if night_mode_end else none %}
        {% set is_night_mode = false %}
        {% if start and end %}
          {% if start > end %}
            {% set is_night_mode = now() >= start or now() < end %}
          {% else %}
            {% set is_night_mode = start <= now() < end %}
          {% endif %}
        {% endif %}
        {{ night_mode_color_temp if is_night_mode else color_temp }}
    target: !input light_target
  - wait_for_trigger:
    - platform: state
      entity_id: !input motion_entity
      to: "off"
      for:
        minutes: !input minutes
  - if: !input turn_off_condition_block
    then:
    - service: light.turn_off
      data: {}
      target: !input light_target